version: 0.0
os: linux
files:
  - source: /wordpress/
    destination: /var/www/html  
hooks:
  BeforeInstall:
    - location: scripts/start
      timeout: 300
      runas: root
  AfterInstall:
    - location: scripts/after
      timeout: 300
      runas: root
