#!/bin/bash
sudo apt-get install apache2 -y
sudo apt-get install php7.0 php7.0-mysql libapache2-mod-php7.0 php7.0-cli php7.0-cgi php7.0-gd -y
FILE=/var/www/html/index.html
if [ -f $FILE ];
then
   sudo rm /var/www/html/index.html
fi
FILE=/etc/apache2/sites-available/000-default.conf
if [ -f $FILE ];
then
  sudo rm /etc/apache2/sites-available/000-default.conf
fi

